// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKWCDTKUAtnjwr0WNJaS0HRWrtt67URk',
    appId: '1:793383945798:web:3335db4ee3bf38ca946c47',
    messagingSenderId: '793383945798',
    projectId: 'tikare-62061',
    authDomain: 'tikare-62061.firebaseapp.com',
    storageBucket: 'tikare-62061.firebasestorage.app',
    measurementId: 'G-P58670TJLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2o3MEby8QaBRzwxa3xm-x-R4ITBNbIOI',
    appId: '1:793383945798:android:cf384582634d46d9946c47',
    messagingSenderId: '793383945798',
    projectId: 'tikare-62061',
    storageBucket: 'tikare-62061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGYTDZNcR4ZjCUWHWk7FS4oLAjvASPTs0',
    appId: '1:793383945798:ios:1089891d86349a1d946c47',
    messagingSenderId: '793383945798',
    projectId: 'tikare-62061',
    storageBucket: 'tikare-62061.firebasestorage.app',
    iosBundleId: 'com.example.tikare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGYTDZNcR4ZjCUWHWk7FS4oLAjvASPTs0',
    appId: '1:793383945798:ios:1089891d86349a1d946c47',
    messagingSenderId: '793383945798',
    projectId: 'tikare-62061',
    storageBucket: 'tikare-62061.firebasestorage.app',
    iosBundleId: 'com.example.tikare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSKWCDTKUAtnjwr0WNJaS0HRWrtt67URk',
    appId: '1:793383945798:web:d90c72674a39b5cf946c47',
    messagingSenderId: '793383945798',
    projectId: 'tikare-62061',
    authDomain: 'tikare-62061.firebaseapp.com',
    storageBucket: 'tikare-62061.firebasestorage.app',
    measurementId: 'G-22YCTJMF0R',
  );
}
